"""Session report generator for CTF-GPT.

Generates markdown writeup drafts from agent sessions using Jinja2
templates. Reports include challenge description, tools executed,
key findings, techniques, and hints.

Reports are saved to ~/.ctfgpt/sessions/{session_id}/report.md.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Optional

from jinja2 import Environment, BaseLoader
from rich.console import Console
from rich.markdown import Markdown

from ctfgpt.config import SESSIONS_DIR

console = Console()

# ---------------------------------------------------------------------------
# Jinja2 markdown template
# ---------------------------------------------------------------------------

REPORT_TEMPLATE = """\
# CTF-GPT Session Report

> **Session ID**: {{ session_id }}
> **Date**: {{ timestamp }}
> **Category**: {{ category }}
> **Challenge**: {{ challenge_desc | truncate(200) }}

---

## Challenge Description

{{ challenge_desc }}

---

## Tools Executed

| # | Tool | Command | Result Summary |
|---|------|---------|----------------|
{% for f in findings -%}
| {{ loop.index }} | `{{ f.tool }}` | `{{ f.command | truncate(60) }}` | {{ f.result | truncate(80) }} |
{% endfor %}

---

## Key Findings

{% for f in top_findings -%}
### {{ loop.index }}. {{ f.tool }} (weight: {{ "%.2f" | format(f.weight) }})

**Command**: `{{ f.command }}`

```
{{ f.result }}
```

{% endfor %}

---

## Techniques Detected

{% if techniques -%}
{% for t in techniques -%}
- {{ t }}
{% endfor %}
{% else -%}
_No specific techniques detected._
{% endif %}

---

## Hint Given

{{ hint }}

---

## Dead Ends

{% if dead_ends -%}
| Tool | Command | Reason |
|------|---------|--------|
{% for d in dead_ends -%}
| `{{ d.tool }}` | `{{ d.command | truncate(50) }}` | Weight decayed to {{ "%.2f" | format(d.weight) }} |
{% endfor %}
{% else -%}
_No dead ends recorded._
{% endif %}

---

## Session Statistics

- **Iterations**: {{ iteration }}
- **Active findings**: {{ findings | length }}
- **Dead ends**: {{ dead_ends | length }}
- **Unexplored leads**: {{ unexplored | length }}

---

## References

{% if sources -%}
{% for src in sources -%}
- {{ src }}
{% endfor %}
{% else -%}
_No external sources referenced._
{% endif %}

---

_Generated by CTF-GPT v{{ version }} on {{ timestamp }}_
"""


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------

def generate_report(
    session_id: str,
    hint: str = "",
    sources: list[str] | None = None,
) -> str:
    """Generate a markdown report from a session's blackboard.

    Parameters
    ----------
    session_id:
        Session identifier (e.g. '2024-01-15_14-32-05').
    hint:
        The final hint/response given to the user.
    sources:
        Optional list of source URLs referenced.

    Returns
    -------
    str
        Rendered markdown report.
    """
    from ctfgpt import __version__

    session_dir = SESSIONS_DIR / session_id
    bb_path = session_dir / "blackboard.json"

    # Load blackboard data
    if bb_path.exists():
        with open(bb_path, "r", encoding="utf-8") as f:
            bb_data = json.load(f)
    else:
        bb_data = {
            "category": "unknown",
            "challenge_desc": "",
            "findings": [],
            "unexplored": [],
            "dead_ends": [],
            "iteration": 0,
        }

    # Extract techniques from findings
    techniques = _extract_techniques(bb_data.get("findings", []))

    # Get top findings sorted by weight
    findings = bb_data.get("findings", [])
    top_findings = sorted(findings, key=lambda f: f.get("weight", 0), reverse=True)[:5]

    # Build template context
    context = {
        "session_id": session_id,
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "category": bb_data.get("category", "unknown"),
        "challenge_desc": bb_data.get("challenge_desc", "N/A"),
        "findings": findings,
        "top_findings": top_findings,
        "techniques": techniques,
        "hint": hint or "_No hint recorded._",
        "dead_ends": bb_data.get("dead_ends", []),
        "unexplored": bb_data.get("unexplored", []),
        "iteration": bb_data.get("iteration", 0),
        "sources": sources or [],
        "version": __version__,
    }

    # Render with Jinja2
    env = Environment(loader=BaseLoader(), autoescape=False)
    template = env.from_string(REPORT_TEMPLATE)
    report_md = template.render(**context)

    # Save report
    session_dir.mkdir(parents=True, exist_ok=True)
    report_path = session_dir / "report.md"
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_md)

    return report_md


def print_report(report_md: str) -> None:
    """Render a markdown report to the terminal using Rich."""
    console.print()
    console.print(Markdown(report_md))
    console.print()


def list_reports() -> list[dict]:
    """List all available session reports.

    Returns
    -------
    list[dict]
        List of dicts with keys: session_id, path, timestamp, category.
    """
    reports = []
    if not SESSIONS_DIR.exists():
        return reports

    for session_dir in sorted(SESSIONS_DIR.iterdir(), reverse=True):
        if not session_dir.is_dir():
            continue

        report_path = session_dir / "report.md"
        bb_path = session_dir / "blackboard.json"

        if report_path.exists():
            category = "unknown"
            if bb_path.exists():
                try:
                    with open(bb_path, "r", encoding="utf-8") as f:
                        bb = json.load(f)
                    category = bb.get("category", "unknown")
                except Exception:
                    pass

            reports.append({
                "session_id": session_dir.name,
                "path": str(report_path),
                "timestamp": session_dir.name,
                "category": category,
            })

    return reports


def get_latest_session_id() -> Optional[str]:
    """Get the session ID of the most recent session."""
    if not SESSIONS_DIR.exists():
        return None

    sessions = sorted(
        [d for d in SESSIONS_DIR.iterdir() if d.is_dir()],
        reverse=True,
    )
    return sessions[0].name if sessions else None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Known technique patterns to detect in findings
_TECHNIQUE_PATTERNS = {
    "SQL Injection": ["sql injection", "sqli", "sqlmap", "' or 1=1"],
    "XSS": ["cross-site scripting", "xss", "<script>"],
    "Buffer Overflow": ["buffer overflow", "bof", "stack smashing", "segfault"],
    "Directory Traversal": ["path traversal", "../", "lfi", "rfi"],
    "Password Cracking": ["john", "hashcat", "rockyou", "wordlist", "cracked"],
    "Port Scanning": ["nmap", "open port", "port scan"],
    "Directory Bruteforce": ["gobuster", "dirb", "dirbuster", "ffuf"],
    "Steganography": ["stego", "lsb", "steghide", "binwalk", "hidden data"],
    "RSA Attack": ["rsa", "factorization", "small exponent"],
    "ROP Chain": ["rop", "return oriented", "gadget"],
    "Format String": ["format string", "%p", "%x", "%n"],
    "File Analysis": ["file header", "magic bytes", "exiftool", "strings"],
}


def _extract_techniques(findings: list[dict]) -> list[str]:
    """Detect technique names from finding results."""
    found = set()
    all_text = " ".join(
        f.get("result", "") + " " + f.get("command", "")
        for f in findings
    ).lower()

    for technique, keywords in _TECHNIQUE_PATTERNS.items():
        for kw in keywords:
            if kw.lower() in all_text:
                found.add(technique)
                break

    return sorted(found)
